spring:
  application:
    name: hisaabkitaab

  # Database properties
  datasource:
    url: jdbc:postgresql://localhost:5432/hisaabkitaab
    username: hkadmin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  # Email properties
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${ BREVO_MAIL_USER_IDENTIFIER:hisaabKitaab }@smtp-brevo.com
    password: ${ BREVO_SMPTP_KEY:password }
    properties:
      mail:
        smptp:
          auth: true
          starttls:
            enable: true
